### PR TITLE
fix: update dump script for Fedora 36

### PR DESCRIPTION
**Pull request by a9ex**
tl;dr: Updated the `grep` line so that it now works on Fedora 36. :v: 

Documentation has been updated to Fedora 36 (https://github.com/Epitech/dump/commit/26e1ae469bf2182f68df87a2a29557c5509246cc), but not the dump script, which can only be run on Fedora 34. (while September '22 dump was done on 36)

### CODE REVIEW

**Review by AdamBrutsaert — APPROVED** [review]

**Review by pablo-1610 — APPROVED** [review]

**Comment by a9ex** [comment]
My men :handshake:

**Review by capuchegianni — APPROVED** [review]

**Review by AdamBrutsaert — APPROVED** [review]

**Review by pablo-1610 — CHANGES_REQUESTED** [review]
Please be precise in your changes, thx !

**Review by AdamBrutsaert — APPROVED** [review]

**Review by ImPoulpitos — APPROVED** [review]
great work mate

**Review by ImPoulpitos — APPROVED** [review]

**Review by ImPoulpitos — APPROVED** [review]
wow amazing

**Review by EwanEpitech — APPROVED** [review]

**Review by Clement-Z4RM — APPROVED** [review]

**Review by isaaclevypiquet — APPROVED** [review]

**Review by AnttonBarquin — APPROVED** [review]

**Review by AnttonBarquin — APPROVED** [review]

**Review by ThibaultLonguepee — APPROVED** [review]
Wow this has changed my life for the better. Thank you so much...

**Review by nicolas-jacquemin — APPROVED** [review]
incredible update

**Review by dandan2611 — APPROVED** [review]
Looks good. Keep going!

**Comment by pablo-1610** [comment]
Can't wait for it 😍

**Review by AugustinPif — APPROVED** [review]

**Review by AlexisSalaun — APPROVED** [review]

**Review by pablo-1610 — APPROVED** [review]

**Review by isaaclevypiquet — APPROVED** [review]
vraiment important materclass

**Review by Atrex05 — APPROVED** [review]

**Review by ThibaultLonguepee — APPROVED** [review]
Top 5 reasons why this should be merged:

1. It's a fix
2. 36 > 34
3. It's a1ex
4. Wait no it's a9ex
5. It's a fix (please merge)

**Review by Sprk3lzZ — APPROVED** [review]
Because it's our project ! 
Emanuel Macron.

**Review by zowks — APPROVED** [review]

**Review by AdamBrutsaert — APPROVED** [review]

**Review by pablo-1610 — APPROVED** [review]

**Comment by a9ex** [comment]
Closing, see https://github.com/Epitech/dump/pull/25

**Comment by a9ex** [comment]
Bon stage à tous btw

**Pull request closed without merging**
